import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Instrument_Serif } from "next/font/google";
import CustomCursor from "./components/CustomCursor";
import WebScroller from "./components/WebScroller";


const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"], // You can add more weights if available
  style: ["normal", "italic"], // because it supports italic too
  variable: "--font-instrument-serif", // custom CSS variable name
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={instrumentSerif.variable}>
      <body
        className={poppins.variable} 
      >
        <WebScroller>
          <CustomCursor />
          {children}
        </WebScroller>
      </body>
    </html>
  );
}
